spring:
  redis:
    database: 5
    host: 192.168.0.121
#    host: 172.20.0.130
    port: 6379
    timeout: 5000
    password:
#    jedis:
#      pool:
#        max-idle: 10
#        min-idle: 0
#        max-active: 10
#        max-wait: 5000
    lettuce:
      pool:
        max-idle: 9
        min-idle: 1
        max-active: 9
        max-wait: 5000